CREATE DATABASE secureAtm;

USE secureAtm;

CREATE TABLE empresa (
	id INT PRIMARY KEY AUTO_INCREMENT,
	razao_social VARCHAR(50),
	cnpj VARCHAR(14)
);

CREATE TABLE usuario (
	id INT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50),
	email VARCHAR(50),
	senha VARCHAR(50),
	fk_empresa INT,
	FOREIGN KEY (fk_empresa) REFERENCES empresa(id)
);
	CREATE TABLE CPUS(
	idCpu INT PRIMARY KEY AUTO_INCREMENT,
	CPU1 VARCHAR(45),
	CPU2 FLOAT,
	CPU3 float,
	momento DATETIME
	);
    
    CREATE TABLE MEMO(
	idCpu INT PRIMARY KEY AUTO_INCREMENT,
	MEMO1 FLOAT,
	MEMO2 FLOAT,
	MEMO3 float,
    momento DATETIME

	);
    
    CREATE TABLE DISCO(
    idDisco INT PRIMARY KEY AUTO_INCREMENT,
    DISCO1 FLOAT,
    DISCO2 FLOAT,
    DISCO3 float,
	momento DATETIME
    );